jobs:
- name: unit-tests
  serial: true
  public: true
  plan:
  - get: concourse-pipeline-samples
    trigger: true
    run:
        path: /bin/bash
        args:
        - -exc
        - |
          pwd
          npm install
          npm start
resources:
- name: concourse-pipeline-samples
  type: git
  source:
    branch: master
    uri: https://github.com/dhaneshande/pullandrundockerimage.git
