---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: dhaneshande/nodecf
    tag: "latest"

inputs:
- name: concourse-pipeline-samples

run:
  path: concourse-pipeline-samples/tasks/run-unit-tests
